# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'almalinux/9'
  config.vm.provider 'libvirt' do |vb|
    vb.memory = 768
    vb.cpus = 1
  end
  config.vm.synced_folder('.', '/vagrant', disabled: true)
end

